name: Generate Sitemap

on:
  push:
    branches: [ main ]  # or your default branch name
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight

permissions:
  contents: write

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Generate Sitemap
      run: python generate_sitemap.py
    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sitemap.xml
        git commit -m "Update sitemap" -a || echo "No changes to commit"
        git push